Use libxml2 to create XML based reports of host stats.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -677,6 +677,8 @@ am__untar
 PKG_CONFIG
 GLIB_CFLAGS
 GLIB_LIBS
+LIBXML2_CFLAGS
+LIBXML2_LIBS
 CC
 CFLAGS
 LDFLAGS
@@ -711,6 +713,8 @@ target_alias
 PKG_CONFIG
 GLIB_CFLAGS
 GLIB_LIBS
+LIBXML2_CFLAGS
+LIBXML2_LIBS
 CC
 CFLAGS
 LDFLAGS
@@ -1292,6 +1296,7 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-xmlreport      Include XML reports.
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-tclfilter      Include Tcl interpreter.
@@ -1305,6 +1310,10 @@ Some influential environment variables:
   PKG_CONFIG  path to pkg-config utility
   GLIB_CFLAGS C compiler flags for GLIB, overriding pkg-config
   GLIB_LIBS   linker flags for GLIB, overriding pkg-config
+  LIBXML2_CFLAGS
+              C compiler flags for LIBXML2, overriding pkg-config
+  LIBXML2_LIBS
+              linker flags for LIBXML2, overriding pkg-config
   CC          C compiler command
   CFLAGS      C compiler flags
   LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
@@ -2404,6 +2413,101 @@ else
 echo "${ECHO_T}yes" >&6; }
 	enable_glib_=yes
 fi
+
+{ echo "$as_me:$LINENO: checking --enable-xmlreport argument" >&5
+echo $ECHO_N "checking --enable-xmlreport argument... $ECHO_C" >&6; }
+# Check whether --enable-xmlreport was given.
+if test "${enable_xmlreport+set}" = set; then
+  enableval=$enable_xmlreport; enable_xmlreport="yes"
+else
+  enable_xmlreport="no"
+fi
+
+{ echo "$as_me:$LINENO: result: $enable_xmlreport" >&5
+echo "${ECHO_T}$enable_xmlreport" >&6; }
+if test "$enable_xmlreport" = "yes"; then
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for LIBXML2" >&5
+echo $ECHO_N "checking for LIBXML2... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$LIBXML2_CFLAGS"; then
+        pkg_cv_LIBXML2_CFLAGS="$LIBXML2_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\"libxml-2.0\"\"") >&5
+  ($PKG_CONFIG --exists --print-errors ""libxml-2.0"") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LIBXML2_CFLAGS=`$PKG_CONFIG --cflags ""libxml-2.0"" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$LIBXML2_LIBS"; then
+        pkg_cv_LIBXML2_LIBS="$LIBXML2_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\"libxml-2.0\"\"") >&5
+  ($PKG_CONFIG --exists --print-errors ""libxml-2.0"") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LIBXML2_LIBS=`$PKG_CONFIG --libs ""libxml-2.0"" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        LIBXML2_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors ""libxml-2.0""`
+        else
+	        LIBXML2_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors ""libxml-2.0""`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$LIBXML2_PKG_ERRORS" >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+                skip_xmlreport=yes
+elif test $pkg_failed = untried; then
+	skip_xmlreport=yes
+else
+	LIBXML2_CFLAGS=$pkg_cv_LIBXML2_CFLAGS
+	LIBXML2_LIBS=$pkg_cv_LIBXML2_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	skip_xmlreport=no
+fi
+
+    if test "$skip_xmlreport" = "no"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define FEAT_XMLREPORT 1
+_ACEOF
+
+    fi
+fi
+
+
 
 
 
@@ -6400,6 +6504,8 @@ am__untar!$am__untar$ac_delim
 PKG_CONFIG!$PKG_CONFIG$ac_delim
 GLIB_CFLAGS!$GLIB_CFLAGS$ac_delim
 GLIB_LIBS!$GLIB_LIBS$ac_delim
+LIBXML2_CFLAGS!$LIBXML2_CFLAGS$ac_delim
+LIBXML2_LIBS!$LIBXML2_LIBS$ac_delim
 CC!$CC$ac_delim
 CFLAGS!$CFLAGS$ac_delim
 LDFLAGS!$LDFLAGS$ac_delim
@@ -6429,7 +6535,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 88; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 90; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
